//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRWBPostpaidPayments.SRWBService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class AifFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomDetailXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SRWBPostpaidPayments.SRWBService.FaultMessageList[] FaultMessageListArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SRWBPostpaidPayments.SRWBService.InfologMessage[] InfologMessageListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XppExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml {
            get {
                return this.CustomDetailXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDetailXmlField, value) != true)) {
                    this.CustomDetailXmlField = value;
                    this.RaisePropertyChanged("CustomDetailXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SRWBPostpaidPayments.SRWBService.FaultMessageList[] FaultMessageListArray {
            get {
                return this.FaultMessageListArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageListArrayField, value) != true)) {
                    this.FaultMessageListArrayField = value;
                    this.RaisePropertyChanged("FaultMessageListArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SRWBPostpaidPayments.SRWBService.InfologMessage[] InfologMessageList {
            get {
                return this.InfologMessageListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfologMessageListField, value) != true)) {
                    this.InfologMessageListField = value;
                    this.RaisePropertyChanged("InfologMessageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType {
            get {
                return this.XppExceptionTypeField;
            }
            set {
                if ((this.XppExceptionTypeField.Equals(value) != true)) {
                    this.XppExceptionTypeField = value;
                    this.RaisePropertyChanged("XppExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessageList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SRWBPostpaidPayments.SRWBService.FaultMessage[] FaultMessageArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlPositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation {
            get {
                return this.DocumentOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentOperationField, value) != true)) {
                    this.DocumentOperationField = value;
                    this.RaisePropertyChanged("DocumentOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SRWBPostpaidPayments.SRWBService.FaultMessage[] FaultMessageArray {
            get {
                return this.FaultMessageArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageArrayField, value) != true)) {
                    this.FaultMessageArrayField = value;
                    this.RaisePropertyChanged("FaultMessageArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation {
            get {
                return this.ServiceOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationField, value) != true)) {
                    this.ServiceOperationField = value;
                    this.RaisePropertyChanged("ServiceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter {
            get {
                return this.ServiceOperationParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationParameterField, value) != true)) {
                    this.ServiceOperationParameterField = value;
                    this.RaisePropertyChanged("ServiceOperationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath {
            get {
                return this.XPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XPathField, value) != true)) {
                    this.XPathField = value;
                    this.RaisePropertyChanged("XPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine {
            get {
                return this.XmlLineField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlLineField, value) != true)) {
                    this.XmlLineField = value;
                    this.RaisePropertyChanged("XmlLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition {
            get {
                return this.XmlPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPositionField, value) != true)) {
                    this.XmlPositionField = value;
                    this.RaisePropertyChanged("XmlPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    [System.SerializableAttribute()]
    public partial class InfologMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SRWBPostpaidPayments.SRWBService.InfologMessageType InfologMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SRWBPostpaidPayments.SRWBService.InfologMessageType InfologMessageType {
            get {
                return this.InfologMessageTypeField;
            }
            set {
                if ((this.InfologMessageTypeField.Equals(value) != true)) {
                    this.InfologMessageTypeField = value;
                    this.RaisePropertyChanged("InfologMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceCustomerData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIPostPaymentResponse))]
    public partial class XppObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SRWBPaymentsAPIServiceCustomerData", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class SRWBPaymentsAPIServiceCustomerData : SRWBPostpaidPayments.SRWBService.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal parmAmountOutstandingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmCustomerNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal parmAmountOutstanding {
            get {
                return this.parmAmountOutstandingField;
            }
            set {
                if ((this.parmAmountOutstandingField.Equals(value) != true)) {
                    this.parmAmountOutstandingField = value;
                    this.RaisePropertyChanged("parmAmountOutstanding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCustomerName {
            get {
                return this.parmCustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCustomerNameField, value) != true)) {
                    this.parmCustomerNameField = value;
                    this.RaisePropertyChanged("parmCustomerName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SRWBPaymentsAPIPostPaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class SRWBPaymentsAPIPostPaymentResponse : SRWBPostpaidPayments.SRWBService.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmPaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmStatusDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmPaymentID {
            get {
                return this.parmPaymentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.parmPaymentIDField, value) != true)) {
                    this.parmPaymentIDField = value;
                    this.RaisePropertyChanged("parmPaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmStatusCode {
            get {
                return this.parmStatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.parmStatusCodeField, value) != true)) {
                    this.parmStatusCodeField = value;
                    this.RaisePropertyChanged("parmStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmStatusDescription {
            get {
                return this.parmStatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.parmStatusDescriptionField, value) != true)) {
                    this.parmStatusDescriptionField = value;
                    this.RaisePropertyChanged("parmStatusDescription");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="SRWBService.SRWBPaymentsAPIService")]
    public interface SRWBPaymentsAPIService {
        
        // CODEGEN: Generating message contract since the wrapper name (SRWBPaymentsAPIServiceTransferPaymentRequest) of message SRWBPaymentsAPIServiceTransferPaymentRequest does not match the default value (transferPayment)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRWBPaymentsAPIService/transferPayment", ReplyAction="http://tempuri.org/SRWBPaymentsAPIService/transferPaymentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SRWBPostpaidPayments.SRWBService.AifFault), Action="http://tempuri.org/SRWBPaymentsAPIService/transferPaymentAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentResponse transferPayment(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRWBPaymentsAPIService/transferPayment", ReplyAction="http://tempuri.org/SRWBPaymentsAPIService/transferPaymentResponse")]
        System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentResponse> transferPaymentAsync(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SRWBPaymentsAPIServicePostPaymentRequest) of message SRWBPaymentsAPIServicePostPaymentRequest does not match the default value (postPayment)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRWBPaymentsAPIService/postPayment", ReplyAction="http://tempuri.org/SRWBPaymentsAPIService/postPaymentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SRWBPostpaidPayments.SRWBService.AifFault), Action="http://tempuri.org/SRWBPaymentsAPIService/postPaymentAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentResponse postPayment(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRWBPaymentsAPIService/postPayment", ReplyAction="http://tempuri.org/SRWBPaymentsAPIService/postPaymentResponse")]
        System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentResponse> postPaymentAsync(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SRWBPaymentsAPIServiceReversePaymentRequest) of message SRWBPaymentsAPIServiceReversePaymentRequest does not match the default value (reversePayment)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRWBPaymentsAPIService/reversePayment", ReplyAction="http://tempuri.org/SRWBPaymentsAPIService/reversePaymentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SRWBPostpaidPayments.SRWBService.AifFault), Action="http://tempuri.org/SRWBPaymentsAPIService/reversePaymentAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentResponse reversePayment(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRWBPaymentsAPIService/reversePayment", ReplyAction="http://tempuri.org/SRWBPaymentsAPIService/reversePaymentResponse")]
        System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentResponse> reversePaymentAsync(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SRWBPaymentsAPIServiceQueryAccountRequest) of message SRWBPaymentsAPIServiceQueryAccountRequest does not match the default value (queryAccount)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRWBPaymentsAPIService/queryAccount", ReplyAction="http://tempuri.org/SRWBPaymentsAPIService/queryAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SRWBPostpaidPayments.SRWBService.AifFault), Action="http://tempuri.org/SRWBPaymentsAPIService/queryAccountAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountResponse queryAccount(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRWBPaymentsAPIService/queryAccount", ReplyAction="http://tempuri.org/SRWBPaymentsAPIService/queryAccountResponse")]
        System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountResponse> queryAccountAsync(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRWBPaymentsAPIServiceTransferPaymentRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SRWBPaymentsAPIServiceTransferPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string paymentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string paymentReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public decimal amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string bankAccount;
        
        public SRWBPaymentsAPIServiceTransferPaymentRequest() {
        }
        
        public SRWBPaymentsAPIServiceTransferPaymentRequest(string paymentID, string paymentReference, decimal amount, string bankAccount) {
            this.paymentID = paymentID;
            this.paymentReference = paymentReference;
            this.amount = amount;
            this.bankAccount = bankAccount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRWBPaymentsAPIServiceTransferPaymentResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SRWBPaymentsAPIServiceTransferPaymentResponse {
        
        public SRWBPaymentsAPIServiceTransferPaymentResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRWBPaymentsAPIServicePostPaymentRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SRWBPaymentsAPIServicePostPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string paymentReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string accountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public decimal amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public System.DateTime paymentDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public string paymentMode;
        
        public SRWBPaymentsAPIServicePostPaymentRequest() {
        }
        
        public SRWBPaymentsAPIServicePostPaymentRequest(string paymentReference, string accountNumber, decimal amount, System.DateTime paymentDate, string paymentMode) {
            this.paymentReference = paymentReference;
            this.accountNumber = accountNumber;
            this.amount = amount;
            this.paymentDate = paymentDate;
            this.paymentMode = paymentMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRWBPaymentsAPIServicePostPaymentResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SRWBPaymentsAPIServicePostPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIPostPaymentResponse response;
        
        public SRWBPaymentsAPIServicePostPaymentResponse() {
        }
        
        public SRWBPaymentsAPIServicePostPaymentResponse(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIPostPaymentResponse response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRWBPaymentsAPIServiceReversePaymentRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SRWBPaymentsAPIServiceReversePaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string paymentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string paymentReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string accountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public decimal amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public System.DateTime paymentDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=5)]
        public string paymentMode;
        
        public SRWBPaymentsAPIServiceReversePaymentRequest() {
        }
        
        public SRWBPaymentsAPIServiceReversePaymentRequest(string paymentID, string paymentReference, string accountNumber, decimal amount, System.DateTime paymentDate, string paymentMode) {
            this.paymentID = paymentID;
            this.paymentReference = paymentReference;
            this.accountNumber = accountNumber;
            this.amount = amount;
            this.paymentDate = paymentDate;
            this.paymentMode = paymentMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRWBPaymentsAPIServiceReversePaymentResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SRWBPaymentsAPIServiceReversePaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIPostPaymentResponse response;
        
        public SRWBPaymentsAPIServiceReversePaymentResponse() {
        }
        
        public SRWBPaymentsAPIServiceReversePaymentResponse(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIPostPaymentResponse response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRWBPaymentsAPIServiceQueryAccountRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SRWBPaymentsAPIServiceQueryAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string accountNumber;
        
        public SRWBPaymentsAPIServiceQueryAccountRequest() {
        }
        
        public SRWBPaymentsAPIServiceQueryAccountRequest(string accountNumber) {
            this.accountNumber = accountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRWBPaymentsAPIServiceQueryAccountResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SRWBPaymentsAPIServiceQueryAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceCustomerData response;
        
        public SRWBPaymentsAPIServiceQueryAccountResponse() {
        }
        
        public SRWBPaymentsAPIServiceQueryAccountResponse(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceCustomerData response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SRWBPaymentsAPIServiceChannel : SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SRWBPaymentsAPIServiceClient : System.ServiceModel.ClientBase<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService>, SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService {
        
        public SRWBPaymentsAPIServiceClient() {
        }
        
        public SRWBPaymentsAPIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SRWBPaymentsAPIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRWBPaymentsAPIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRWBPaymentsAPIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentResponse SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService.transferPayment(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentRequest request) {
            return base.Channel.transferPayment(request);
        }
        
        public void transferPayment(string paymentID, string paymentReference, decimal amount, string bankAccount) {
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentRequest inValue = new SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentRequest();
            inValue.paymentID = paymentID;
            inValue.paymentReference = paymentReference;
            inValue.amount = amount;
            inValue.bankAccount = bankAccount;
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentResponse retVal = ((SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService)(this)).transferPayment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentResponse> SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService.transferPaymentAsync(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentRequest request) {
            return base.Channel.transferPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentResponse> transferPaymentAsync(string paymentID, string paymentReference, decimal amount, string bankAccount) {
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentRequest inValue = new SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceTransferPaymentRequest();
            inValue.paymentID = paymentID;
            inValue.paymentReference = paymentReference;
            inValue.amount = amount;
            inValue.bankAccount = bankAccount;
            return ((SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService)(this)).transferPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentResponse SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService.postPayment(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentRequest request) {
            return base.Channel.postPayment(request);
        }
        
        public SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIPostPaymentResponse postPayment(string paymentReference, string accountNumber, decimal amount, System.DateTime paymentDate, string paymentMode) {
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentRequest inValue = new SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentRequest();
            inValue.paymentReference = paymentReference;
            inValue.accountNumber = accountNumber;
            inValue.amount = amount;
            inValue.paymentDate = paymentDate;
            inValue.paymentMode = paymentMode;
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentResponse retVal = ((SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService)(this)).postPayment(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentResponse> SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService.postPaymentAsync(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentRequest request) {
            return base.Channel.postPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentResponse> postPaymentAsync(string paymentReference, string accountNumber, decimal amount, System.DateTime paymentDate, string paymentMode) {
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentRequest inValue = new SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServicePostPaymentRequest();
            inValue.paymentReference = paymentReference;
            inValue.accountNumber = accountNumber;
            inValue.amount = amount;
            inValue.paymentDate = paymentDate;
            inValue.paymentMode = paymentMode;
            return ((SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService)(this)).postPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentResponse SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService.reversePayment(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentRequest request) {
            return base.Channel.reversePayment(request);
        }
        
        public SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIPostPaymentResponse reversePayment(string paymentID, string paymentReference, string accountNumber, decimal amount, System.DateTime paymentDate, string paymentMode) {
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentRequest inValue = new SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentRequest();
            inValue.paymentID = paymentID;
            inValue.paymentReference = paymentReference;
            inValue.accountNumber = accountNumber;
            inValue.amount = amount;
            inValue.paymentDate = paymentDate;
            inValue.paymentMode = paymentMode;
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentResponse retVal = ((SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService)(this)).reversePayment(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentResponse> SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService.reversePaymentAsync(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentRequest request) {
            return base.Channel.reversePaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentResponse> reversePaymentAsync(string paymentID, string paymentReference, string accountNumber, decimal amount, System.DateTime paymentDate, string paymentMode) {
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentRequest inValue = new SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceReversePaymentRequest();
            inValue.paymentID = paymentID;
            inValue.paymentReference = paymentReference;
            inValue.accountNumber = accountNumber;
            inValue.amount = amount;
            inValue.paymentDate = paymentDate;
            inValue.paymentMode = paymentMode;
            return ((SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService)(this)).reversePaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountResponse SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService.queryAccount(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountRequest request) {
            return base.Channel.queryAccount(request);
        }
        
        public SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceCustomerData queryAccount(string accountNumber) {
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountRequest inValue = new SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountRequest();
            inValue.accountNumber = accountNumber;
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountResponse retVal = ((SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService)(this)).queryAccount(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountResponse> SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService.queryAccountAsync(SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountRequest request) {
            return base.Channel.queryAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountResponse> queryAccountAsync(string accountNumber) {
            SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountRequest inValue = new SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIServiceQueryAccountRequest();
            inValue.accountNumber = accountNumber;
            return ((SRWBPostpaidPayments.SRWBService.SRWBPaymentsAPIService)(this)).queryAccountAsync(inValue);
        }
    }
}
