//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRWBPostpaidPayments.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostPaidException
    {
        public long Id { get; set; }
        public string InnerMessage { get; set; }
        public string Method { get; set; }
        public string Class { get; set; }
        public string SignedInUser { get; set; }
        public System.DateTime DateGenerated { get; set; }
        public string System { get; set; }
    }
}
