//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRWBPostpaidPayments.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long RecordID { get; set; }
        public string FundingAcct { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNumber { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string StatusDescription { get; set; }
        public string PaymentId { get; set; }
        public string PaymentReference { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AccessingPhone { get; set; }
        public string FriendlyName { get; set; }
        public string OfsRequest { get; set; }
        public string OfsResponse { get; set; }
        public string TxnRef { get; set; }
        public string ProfileID { get; set; }
        public string EffectivePhone { get; set; }
        public Nullable<bool> Reversed { get; set; }
        public string Message { get; set; }
        public string Teller { get; set; }
    }
}
